apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-postgres
spec:
  type: ClusterIP
  selector:
    app: {{ include "my-app.name" . }}-postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
